SYS AS SYSDBA --> SYS KULLANICISI SYSDBA ROLU ILE SISTEME GIRIS YAPAR. SIFRE GIRILIR.
ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE; --> _ORACLE_SCRIPT DEGERINI TRUE YAPARAK SCRIPT CALISTIRMAMIZI SAGLAR.
CREATE USER HUSEYIN IDENTIFIED BY HUSEYIN; --> HUSEYIN ADINDA YENI BIR KULLANICI OLUSTURUR. SIFRESINI DE HUSEYIN YAPAR.
GRANT CONNECT, RESOURCE TO HUSEYIN; --> HUSEYIN KULLANICISININ BAGLANMA VE KAYNAK YETKISI VAR. YETKI VERILDI.
GRANT CREATE TABLE TO HUSEYIN; --> HUSEYIN KULLANICISINA TABLO OLUSTURABILME YETKISI VERILDI.
GRANT UNLIMITED TABLESPACE TO HUSEYIN; --> LIMITSIZ DOSYA SISTEMI KULLANIMI YETKISI VERILDI.
SHOW PARAMETER LOCAL_LISTENER; --> YEREL DINLEYICI(BAGLANTI DINLEYICISI) PARAMETRELERINI GOSTERIR.
DROP USER MEHMET CASCADE; --> MEHMET ISIMLI USER'I VE NE KADAR NESNESI VARSA SILER.
CREATE TABLE EMPLOYEES(
	EMPNO NUMBER(5),
	NAME VARCHAR2(15),
	HIREDATE DATE,
	SALARY NUMBER(7,2),
	CURRENCY VARCHAR2(3)
); --> ID'SI VE PRIMARY KEY'I DOGAL OLARAKTA INDEX YAPISI OLMAYAN BIR TABLO OLUSTURDUK.
DESC EMPLOYEES; --> TABLO YAPISINI VERIR. BU YAPI BIZE TABLO HAKKINDA ACIKLAYICI BIR BILGI VERIR.
SELECT * FROM EMPLOYEES; --> CALISANLAR TABLOSUNUN TUM KOLONLARINI OKUR VE YAZAR.
INSERT INTO EMPLOYEES VALUES(100, 'HUSEYIN AYDIN', TO_DATE('23/04/49', 'DD/MM/YY'), 5000, '₺'); --> EMPLOYEES TABLOSUNA 1 SATIRLIK VERI GIRDIK.
ROLLBACK; --> YAPILAN ISLEM COMMIT(KALICI) HALE GETIRILMEDEN ONCE GERI ALIR.
INSERT INTO EMPLOYEES(EMPNO, NAME, HIREDATE, SALARY, CURRENCY) VALUES(100, 'HUSEYIN AYDIN', TO_DATE('23/04/49', 'DD/MM/YY'), 5000, '₺'); --> EMPLOYEES TABLOSUNA 1 SATIRLIK VERI GIRDIK.
ED --> EDITOR DEMEKTIR. SON YAZILAN KOMUTU NOTPAD ILE ACAR DUZENLEMEMIZ ICIN. DAHA RAHAT DUZENLEME VE KONFOR SAGLAMASI ICINDIR.
R --> DUZENLENMIS OLAN KOMUTU CALISTIRIR.
/ --> DUZENLENMIS OLAN KOMUTU CALISTIRIR.
COMMIT; --> SULTAN ABDULHAMIT HAN'IN MUHRUDUR. VERIYI KALICI HALE GETIRIR. DIKKATLI OLUNMASI LAZIM ROLLBACK YAPILMASI GEREKEN DURUMDA COMMIT YAPILIRSA DEGISIKLIK GERI ALINAMAZ.

INSERT INTO EMPLOYEES(EMPNO, NAME, HIREDATE, SALARY, CURRENCY)
VALUES(&EMPNO, &NAME, &HIREDATE, &SALARY, &CURRENCY); --> KULLANICIDAN ETKILESINLI VE PARAMETRIK OLARAK VERI ALIP EMPLOYEES TABLOSUNA KAYIT ETTIK.

START C:\Users\Huseyin_Aydin\Desktop\emp_dept.sql --> ILGILI SQL BETIGINI CALISTIRIR.
@C:\Users\Huseyin_Aydin\Desktop\emp_dept.sql --> ILGILI SQL BETIGINI CALISTIRIR.

CREATE TABLE ILLER(
	ILKODU NUMBER(3),
	ILADI VARCHAR2(30)
);

INSERT INTO ILLER(ILKODU, ILADI) VALUES(6, 'ANKARA');
INSERT INTO ILLER(ILKODU, ILADI) VALUES(34, 'ISTANBUL');
COMMIT;

CL SCR; --> CLEAR SCREEN EKRANI TEMIZLE KOMUTU. BIRAZ SACMA SADECE CLEAR OLSA DAHA IYI OLURMUS SANKI. :D
DESC ILLER; --> ILLER TABLOSUNUN ACIKLAMASINI VERIR. TABLO YAPISINI.

SELECT USER FROM DUAL; --> HANGI KULLANICI ILE LOGININIZ ONUR VERIR.
SELECT TABLE_NAME FROM TABS; --> BU SEMA ICERISINDE KI TUM TABLOLARI GETIRIR.

