SYS AS SYSDBA --> SYS KULLANICISI SYSDBA ROLU ILE SISTEME GIRIS YAPAR. SIFRE GIRILIR.
ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE; --> _ORACLE_SCRIPT DEGERINI TRUE YAPARAK SCRIPT CALISTIRMAMIZI SAGLAR.
CREATE USER HUSEYIN IDENTIFIED BY HUSEYIN; --> HUSEYIN ADINDA YENI BIR KULLANICI OLUSTURUR. SIFRESINI DE HUSEYIN YAPAR.
GRANT CONNECT, RESOURCE TO HUSEYIN; --> HUSEYIN KULLANICISININ BAGLANMA VE KAYNAK YETKISI VAR. YETKI VERILDI.
GRANT CREATE TABLE TO HUSEYIN; --> HUSEYIN KULLANICISINA TABLO OLUSTURABILME YETKISI VERILDI.
GRANT UNLIMITED TABLESPACE TO HUSEYIN; --> LIMITSIZ DOSYA SISTEMI KULLANIMI YETKISI VERILDI.
SHOW PARAMETER LOCAL_LISTENER; --> YEREL DINLEYICI(BAGLANTI DINLEYICISI) PARAMETRELERINI GOSTERIR.
DROP USER MEHMET CASCADE; --> MEHMET ISIMLI USER'I VE NE KADAR NESNESI VARSA SILER.
CREATE TABLE EMPLOYEES(
	EMPNO NUMBER(5),
	NAME VARCHAR2(15),
	HIREDATE DATE,
	SALARY NUMBER(7,2),
	CURRENCY VARCHAR2(3)
); --> ID'SI VE PRIMARY KEY'I DOGAL OLARAKTA INDEX YAPISI OLMAYAN BIR TABLO OLUSTURDUK.
DESC EMPLOYEES; --> TABLO YAPISINI VERIR. BU YAPI BIZE TABLO HAKKINDA ACIKLAYICI BIR BILGI VERIR.
SELECT * FROM EMPLOYEES; --> CALISANLAR TABLOSUNUN TUM KOLONLARINI OKUR VE YAZAR.
INSERT INTO EMPLOYEES VALUES(100, 'HUSEYIN AYDIN', TO_DATE('23/04/49', 'DD/MM/YY'), 5000, '₺'); --> EMPLOYEES TABLOSUNA 1 SATIRLIK VERI GIRDIK.
ROLLBACK; --> YAPILAN ISLEM COMMIT(KALICI) HALE GETIRILMEDEN ONCE GERI ALIR.
INSERT INTO EMPLOYEES(EMPNO, NAME, HIREDATE, SALARY, CURRENCY) VALUES(100, 'HUSEYIN AYDIN', TO_DATE('23/04/49', 'DD/MM/YY'), 5000, '₺'); --> EMPLOYEES TABLOSUNA 1 SATIRLIK VERI GIRDIK.
ED --> EDITOR DEMEKTIR. SON YAZILAN KOMUTU NOTPAD ILE ACAR DUZENLEMEMIZ ICIN. DAHA RAHAT DUZENLEME VE KONFOR SAGLAMASI ICINDIR.
R --> DUZENLENMIS OLAN KOMUTU CALISTIRIR.
/ --> DUZENLENMIS OLAN KOMUTU CALISTIRIR.
COMMIT; --> SULTAN ABDULHAMIT HAN'IN MUHRUDUR. VERIYI KALICI HALE GETIRIR. DIKKATLI OLUNMASI LAZIM ROLLBACK YAPILMASI GEREKEN DURUMDA COMMIT YAPILIRSA DEGISIKLIK GERI ALINAMAZ.

INSERT INTO EMPLOYEES(EMPNO, NAME, HIREDATE, SALARY, CURRENCY)
VALUES(&EMPNO, &NAME, &HIREDATE, &SALARY, &CURRENCY); --> KULLANICIDAN ETKILESINLI VE PARAMETRIK OLARAK VERI ALIP EMPLOYEES TABLOSUNA KAYIT ETTIK.

START C:\Users\Huseyin_Aydin\Desktop\emp_dept.sql --> ILGILI SQL BETIGINI CALISTIRIR.
@C:\Users\Huseyin_Aydin\Desktop\emp_dept.sql --> ILGILI SQL BETIGINI CALISTIRIR.

CREATE TABLE ILLER(
	ILKODU NUMBER(3),
	ILADI VARCHAR2(30)
);

INSERT INTO ILLER(ILKODU, ILADI) VALUES(6, 'ANKARA');
INSERT INTO ILLER(ILKODU, ILADI) VALUES(34, 'ISTANBUL');
COMMIT;

CL SCR; --> CLEAR SCREEN EKRANI TEMIZLE KOMUTU. BIRAZ SACMA SADECE CLEAR OLSA DAHA IYI OLURMUS SANKI. :D
DESC ILLER; --> ILLER TABLOSUNUN ACIKLAMASINI VERIR. TABLO YAPISINI.

SELECT USER FROM DUAL; --> HANGI KULLANICI ILE LOGININIZ ONUR VERIR.
SELECT TABLE_NAME FROM TABS; --> BU SEMA ICERISINDE KI TUM TABLOLARI GETIRIR.

SELECT * FROM EMP;
SELECT * FROM EMP WHERE SAL < 1000; --> MAASI 1000 DEGERINDEN KUCUK OLANLARI OKUR.
SELECT * FROM EMP WHERE SAL > 1000; --> MAASI 1000 DEGERINDEN BUYUK OLANLARI OKUR.
SELECT * FROM EMP WHERE NOT (COMM BETWEEN 300 AND 500); --> KOMISYONU 300 VE 500'UN ARASINDA OLMAYANLARI GETIREN SORGUDUR.
SELECT * FROM EMP WHERE JOB = 'SALESMAN' AND SAL = 1000; --> MESLEGI SATICI VE MAASI 1000 ₺ OLANLARI OKUR.
SELECT * FROM EMP WHERE DEPTNO IN(20, 30); --> DEPNO'SU 20 30 OLANLARI GETIRIR.
SELECT * FROM EMP WHERE DEPTNO NOT IN(20, 30); --> DEPNO'SU 20 30 OLMAYANLARI GETIRIR.
SELECT * FROM EMP WHERE COMM IS NULL; --> KOMISYON KOLONU NULL OLANLARI GETIRIR. NULL YOKLUK DEMEKTIR. BOSLUK KARAKTERI NULL DEMEK DEGILDIR. BOSLUK KARAKTERI DE ASLINDA VARDIR YANI VARLIKTIR. NULL ISE BOSLUK BILE OLMAMASI ANLAMINA GELMEKTEDIR. O KADAR YOKLUK YANI.
SELECT * FROM EMP WHERE COMM IS NOT NULL; --> NULL OLMAYANLARI GETRIR.
SELECT * FROM DEPT D WHERE EXISTS(SELECT * FROM EMP E WHERE E.DEPTNO = D.DEPTNO);
SELECT * FROM DEPT D WHERE NOT EXISTS(SELECT * FROM EMP E WHERE E.DEPTNO = D.DEPTNO);
SELECT * FROM EMP WHERE DEPTNO = 40; --> DEPTNO'SU 40 OLANLARI GETIRIR.
SELECT * FROM EMP WHERE ENAME LIKE 'J%'; --> ENAME KOLONU BAS HARFI J OLAN KAYDI GETIRIR.
SELECT * FROM EMP WHERE ENAME LIKE '%S'; --> ENAME KOLONU SON HARFI S OLAN KAYDI GETIRIR.
SELECT * FROM EMP WHERE ENAME LIKE '%S%'; --> ENAME KOLONU ICINDE S HARFI OLAN KAYDI GETIRIR.
SELECT * FROM EMP WHERE ENAME LIKE 'J%S'; --> ENAME KOLONU J ILE BASLAYIP S ILE BITEN KAYITLARI GETIRIR.
SELECT * FROM EMP WHERE ENAME LIKE '_S%'; --> ENAME KOLONU ILK HARFI NE OLURSA OLSUN ONEMLI DEGIL 2. KARAKTERI S OLANI GETIR.
SELECT * FROM EMP WHERE ENAME LIKE '%S_'; --> ENAME KOLONU SON HARFI NE OLURSA OLSUN ONEMLI DEGIL SONDAN 2. KARAKTERI S OLANI GETIR.
SELECT * FROM ALL_USERS; --> ALL_USERS TABLOSUNU YANI TUM KULLANICILAR TABLOSUNU OKUR. TUN KULLANICILAR EKRANA YAZILIR.
SET LINESIZE 200; --> BIR SATIRDA BULUNACAK KARAKTER YANI KOLON SAYISINI SET EDER YANI YARLAR. BOYLELIKLE DUZGUN BIR FORMATTA CIKTI ALINIR.
COL USERNAME FORMAT A30; --> USERNAME KOLONUNU A30(30 KARAKTER) SEKLINDE FORMATLAR.
COL USERNAME FOR A50; --> USERNAME KOLONUNU A50(50 KARAKTER) SEKLINDE FORMATLAR.
COL SAL FOR 999,999,999,999; --> MAAS KOLONUNU FORMATLAR.
ALTER SESSION SET NLS_DATE_FORMAT = 'DD-MON-YYYY'; --> TARIH FORMATINI GUN - AY - YIL SEKLINDE FORMATLAR.
ALTER SESSION SET NLS_DATE_FORMAT = 'DD-MON-YYYY HH24:MI:SS'; --> TARIH FORMATINI GUN - AY - YIL 24SAAT - DAKIKA - SANIYE SEKLINDE FORMATLAR.
SELECT * FROM EMP ORDER BY DEPTNO; --> DEPTNO KOLONUNA GORE SIRALAMA YAPAR.
DESC EMP; --> EMP TABLOSUNUN ACIKLAMASINI VERIR. TABLO YAPISINI VERIR.
SELECT * FROM EMP ORDER BY 8; --> 8 NUMARALI KOLONA GORE SIRALAMA YAPAR. VARSAYILANI ASC'DIR.
SELECT * FROM EMP ORDER BY 8 ASC; --> ARTAN SIRADA. ABC... 123...
SELECT * FROM EMP ORDER BY 8 ASC; --> AZALAN SIRADA. Z...  987...
SELECT * FROM EMP ORDER BY DEPTNO DESC, EMPNO ASC; --> DEPTNO'A GORE AZALAN. EMPNO'A GORE ARTAN SIRALAMA YAPAR.
SELECT ABS(90), ABS(-90) FROM DUAL; --> ABS(ABSOLUTE(MUTLAK DEGER))(+90 GIRERSEN +90'I ALIRSIN. -90 GIRERSEN +90'I ALIRSIN. ARTIYA ARTI CIKTI VERIR. EKSIYE ARTI CIKTI VERIR).
SELECT ACOS(0.4) FROM DUAL; -->ACOS COS'UN TERSIDIR. ANORMAL GIBI(NORMAL'IN TERSI). 
SELECT CEIL(5.000001) FROM DUAL; --> YUKARI YUVARLAMA. 6 DEGERINE YUVARLAR.
SELECT FLOOR(0.4) FROM DUAL; --> ASAGI YUVARLAMA. 0 DEGERINE YUVARLAR.
SELECT MOD(35, 6) MOD FROM DUAL; --> GIRILEN IKI SAYIDAN BIRINCISININ IKINCISINE BOLUMUNDEN KALANI VERIR.
SELECT POWER(10, 2) FROM DUAL; --> POWER KUVVET DEMEKTIR. 1. PARAMETRE USSU 2. PARAMETREDIR.
SELECT EXP(20) FROM DUAL; --> E USSU N SAYISINI DONDURUR. E SAYISI PI GIBI SABIT BIR SAYIDIR. E USSU 20 = 485165195,409790277969106830541540558697



















_